### ISSUE TITLE
The output of calculate_force_and_torque_matrix is resistance_matrix, not the force and torque matrix

### ISSUE THREAD

**Issue by FrankHuwei** [Philipp-MR/CoilGen#5]
The output of calculate_force_and_torque_matrix is **resistance_matrix**, not the **force and torque matrix**. And the code of calculate_force_and_torque_matrix  nearly same as calculate_resistance_matrix.

**Comment by Philipp-MR** [comment]
The "force and torque matrix" is not finished and actually currently not used in the code. Maybe i will include that feature of force and torque calucation in the future. Currently, i have no time for that.
