### ISSUE TITLE
calculate_inductance_matrix seems run into infinite loop.

### ISSUE THREAD

**Issue by FrankHuwei** [Philipp-MR/CoilGen#7]
I try to add inductance into SF Optimization to get lower inductance. However, it seems run into infinite loop while calculate_inductance_matrix.

**Comment by Philipp-MR** [comment]
Dear Frankhuwai,

It is possible to optimize for lower inductance. In my work however, i always focused on lower resistancy ot increase efficiency. Try to include the inductance_matrix in the cost function in the stream function optimization part. It should work, let me know if you got something there.


Best,
Philipp

**Comment by Philipp-MR** [comment]
Oh, one thing: You need also to debug the calculation of the inductance matrix, it was a code which i started, but nether acutally used it.
