### ISSUE TITLE
B0 direction 

### ISSUE THREAD

**Issue by irecana** [Philipp-MR/CoilGen#9]
Hello, great project! I am trying to build some gradient coils for an axial B0: is this simulation for a transversal or axial main magnetic field? Is there a way to set the B0 orientation? 
I see a "b0_direction" parameter, but that only sets the orientation of the interconnections, is that right?

Any input is highly appreciated!

**Comment by Philipp-MR** [comment]
Hi Irecana,

The B0 direction is per definition always in the z ([0,0,1]) direction. This is the standart MR convention for imaging. For the Halbach configuration, the cylinder support object orientation is changed. So instead changing B0, you can change the orientation of your coil. The result is the same. You can change for the different geometries (cylinder, planar etc.) the orientation with the angle parameters . Best!

**Comment by irecana** [comment]
Got it, thank you!
